version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dsi_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  eureka-ms:
    build: E:\Esprit DSI\Eureka\gs-service-registration-and-discovery-main\complete\eureka-service
    ports:
      - 9091:8761
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port" : "8761",
        "eureka.client.register-with-eureka"  : "false",
        "eureka.client.fetch-registry" : "false",
        "eureka.instance.hostname" : "localhost",
        "logging.level.com.netflix.eureka" : "OFF",
        "logging.level.com.netflix.discovery" : "OFF"
      }'
    volumes:
      - .m2:/root/.m2
  zuul-ms:
    build: E:\Esprit DSI\Zuul
    ports:
      - 9092:8765
    depends_on:
      - eureka-ms
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port" : "8765",
        "zuul.sensitive-headers" : "",
        "zuul.host.connect-timeout-millis" : "10000",
        "zuul.host.socket-timeout-millis" : "10000",
        "zuul.ribbon.ReadTimeout" : "10000",
        "eureka.client.serviceUrl.defaultZone" : "http://eureka-ms:8761/eureka",
        "eureka.client.instance.preferIpAddress" : "true",
        "zuul.routes.userservice-ms.url" : "http://userservice-ms:9093/",
        "zuul.routes.userservice-ms.path" : "/api/user/**",
        "zuul.routes.userservice-ms.sensitive-headers" : "",
        "zuul.routes.authentication-ms.url" : "http://authentication-ms:9090/",
        "zuul.routes.authentication-ms.path" : "/api/auth/**",
        "zuul.routes.authentication-ms.sensitive-headers" : "Cookie,Set-Cookie,Authorization"
      }'
    volumes:
      - .m2:/root/.m2
  authentication-ms:
    depends_on:
      - mysqldb
      - zuul-ms
    build: E:\Esprit DSI\dsi.authentication\Dsi-Esprit-Student-Committee
    restart: on-failure
    ports:
      - 9090:8081
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/dsi_db?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "123456",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.datasource.driver-class-name" : "com.mysql.jdbc.Driver",
        "eureka.client.serviceUrl.defaultZone"  : "http://eureka-ms:8761/eureka",
        "eureka.client.instance.preferIpAddress" : "true",
        "spring.application.name" : "authentication-ms",
        "jwt.secret" : "dsiesprittnstudentcommitteesecretkey25203103906962696",
        "dsi.app.jwtExpirationMs" : "86400000",
        "jwt.jwtCookieName" : "esprit"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  userservice-ms:
    depends_on:
      - mysqldb
      - zuul-ms
    build: E:\Esprit DSI\dsi.esprit.userService
    restart: on-failure
    ports:
      - 9093:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/dsi_db?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "123456",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "spring.datasource.driver-class-name" : "com.mysql.jdbc.Driver",
        "eureka.client.serviceUrl.defaultZone" : "http://eureka-ms:8761/eureka",
        "eureka.client.instance.preferIpAddress" : "true",
        "spring.application.name" : "userservice-ms",
        "jwt.secret" : "dsiesprittnstudentcommitteesecretkey25203103906962696",
        "dsi.app.jwtExpirationMs" : "86400000",
        "jwt.jwtCookieName" : "esprit"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: